development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(:redis, :url) { "redis://localhost:6379/1" } %>
  channel_prefix: mp3downloadr_production
